# Generated by Django 4.1.5 on 2023-03-31 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_checkout_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 30, 14, 46, 44, 530030, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
