# Generated by Django 4.1.5 on 2023-04-04 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 11, 5, 41, 916574, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
