# Generated by Django 4.1.5 on 2023-04-04 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_checkout_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 11, 10, 6, 185680, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
