# Generated by Django 4.1.5 on 2023-04-04 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_checkout_payment_type_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='Payment_type',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 13, 36, 30, 50701, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
