# Generated by Django 4.2 on 2023-04-19 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_checkout_payment_type_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 8, 39, 39, 197280, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
