# Generated by Django 4.2 on 2023-05-17 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 6, 44, 891166, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
