# Generated by Django 5.1.6 on 2025-04-05 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expiration time (of ad)'),
        ),
    ]
